version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name work5-app --s3-location s3://work5-code/artifact.zip --source src
artifacts:
  files:
    - "**/*"
  base-directory: src
